version: "3"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - worker
      - default

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - default
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARE_TUNNEL_TOKEN}"

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
      target: web
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    networks:
      - default
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - tunnel
    volumes:
      - ./prisma/db.sqlite:/app/prisma/db.sqlite

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
      target: worker
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
    networks:
      - worker
    depends_on:
      - redis
    volumes:
      - ./prisma/db.sqlite:/app/prisma/db.sqlite

networks:
  worker:
    name: worker
  default:
